# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Empirical | Dialectic
email: not-happening@noway.com
description: #>- # this means to ignore newlines until "baseurl:"
  Self-prescribed Unconventional Methods for Learning and Discovery
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://antitheses.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iamdionysus
github_username:  suriyadeepan

# Build settings
remote_theme: mmistakes/so-simple-theme
#plugins:
#  - jekyll-feed

locale: "en-us"
logo: "images/logo-at-1.png"
markdown: kramdown
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
read_time: true
words_per_minute: 75
date_format: "%B %-d, %Y"
search_full_content: true
google_analytics: UA-78656027-3
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# plugins:
#   - jekyll-archives
